### PR TITLE
Fix heatmap

### LINKED ISSUE #2307: Pokemon on heatmap not showing up
## Expected Behavior

Heatmap should show pokemon.

## Current Behavior

Pokemon on heatmap are not showing up. Using the developer console on Chrome I got two errors.
First when opening the stats page:
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at app.min.js:5
    at app.min.js:5
```
And the next error occured when opening the heatmap:
```
map.common.min.js:5 Uncaught ReferenceError: isNotifyPoke is not defined
    at setupPokemonMarkerDetails (map.common.min.js:5)
    at setupPokemonMarker (map.common.min.js:5)
    at Object.processAppearance (statistics.min.js:5)
    at Function.each (jquery.min.js:2)
    at Object.<anonymous> (statistics.min.js:5)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```
## Possible Solution

-

## Steps to Reproduce (for bugs)

1.  Open the heatmap...

## Your Environment

Client: Windows 10, Google Chrome Version 61.0.3163.100.
Server: Ubuntu 16.04, Python 2.7.

### PR DESCRIPTION
**Pull request by ChrisSsSsSsS**
this was listed as an Issue on 22.09.2017: #2307 

**Seb:** Fixes #2307.

## Description

There were two issues:
1. in app.js: `Uncaught TypeError: Cannot read property 'appendChild' of null`
2. `map.common.min.js:5 Uncaught ReferenceError: isNotifyPoke is not defined`

Here's are explanations why these two errors occurr:
1. The `TypeError` occurred because on the /stats page you don't have a gym-sidebar, but in the app.js it tries to append a child to the sidebar, without checking:
`$gymSidebar.appendChild($gymSidebarClose)` ([link](https://github.com/RocketMap/RocketMap/blob/develop/static/js/app.js#L100))
2. The `isNotifyPoke is not defined` error happens because the `setupPokemonMarkerDetails` function in `map.common.js` has a cross-reference to a function `isNotifyPoke` which is solely defined in `map.js`. This reference stems from the "scale by rarity" functionality and can be seen in this line
`var rarityValue = isNotifyPoke(item) || (upscaledPokemon.indexOf(item['pokemon_id']) !== -1) ? 29 : 2` ([link](https://github.com/RocketMap/RocketMap/blob/develop/static/js/map.common.js#L1102))

Here are my solutions:
1. I just added a null check
2. You could just add a dummy-function like `function isNotifyPoke(poke) { return false; }` to `statistics.js`, but this doesn't address the real issue: cross-referencing
So instead I pass an optional argument to the `map.common.js` function `setupPokemonMarker` and `updatePokemonMarker`, which toggles if the current item is "worthy of notification"(default: false). I updated the usages in `statistics.js` and `map.js` accordingly

## Motivation and Context

Without this change the heatmap won't work anymore.

## How Has This Been Tested?

I tested the map on my local server and the map seems unaffected(both non-notify and notify pkmn are shown) and on the /stats page the heatmap works like a charm

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: static/js/statistics.js [hunk 1]
```diff
@@ -420,7 +420,7 @@ function processAppearance(i, item) {
         if (item['marker']) {
             item['marker'].setMap(null)
         }
-        item['marker'] = setupPokemonMarker(item, map, true, false)
+        item['marker'] = setupPokemonMarker(item, map, true, false, false)
```
Comment (sebastienvercammen) [inline static/js/statistics.js]: `true, false, false` are not very descriptive. Can you put them in separate variables just above it so we can use the variable names to know what they are w/o looking at the function description?

File: static/js/statistics.js [hunk 2]
```diff
@@ -434,7 +434,7 @@ function redrawAppearances(appearances) {
         var item = appearances[key]
         if (!item['hidden']) {
             item['marker'].setMap(null)
-            const newMarker = setupPokemonMarker(item, map, true, false)
+            const newMarker = setupPokemonMarker(item, map, true, false, false)
```
Comment (sebastienvercammen) [inline static/js/statistics.js]: Same here as above.

File: static/js/map.js [hunk 3]
```diff
@@ -1576,10 +1576,14 @@ function processPokemon(item) {
          !isExcludedPoke && isPokeAlive) {
         // Add marker to map and item to dict.
         if (!item.hidden) {
+            const isBounceDisabled = false
```
Comment (sebastienvercammen) [inline static/js/map.js]: We should get `isBounceDisabled` from `Store`: unlike `scaleByRarity` we don't include the `Store` value.

For `scaleByRarity`, we should remove this line from `map.common.js`:
```
scaleByRarity = scaleByRarity && Store.get('scaleByRarity')
```
move `Store.get('scaleByRarity')` out of the function (for dependency injection: no more function dependency on the `Store`), and use it where appropriate.

Comment (ChrisSsSsSsS) [reply static/js/map.js]: > We should get `isBounceDisabled` from `Store`: unlike `scaleByRarity` we don't include the `Store` value.
What exactly do you mean by that, should I add a store value for `isBounceDisabled` and move it out of the function like `scaleByRarity`?

Comment (sebastienvercammen) [reply static/js/map.js]: @ChrisSsSsSsS Yes, so its default value can be changed via `custom.js`.

Comment (ChrisSsSsSsS) [reply static/js/map.js]: @sebastienvercammen ok seems reasonable :thumbsup:

File: static/js/statistics.js [hunk 4]
```diff
@@ -417,10 +417,14 @@ function closeOverlay() { // eslint-disable-line no-unused-vars
 function processAppearance(i, item) {
     var spawnpointId = item['spawnpoint_id']
     if (!((spawnpointId) in mapData.appearances)) {
+        const isBounceDisabled = true // we don't need this functionality in our heatmap..
+        const scaleByRarity = false   // ..neither this..
+        const isNotifyPkmn = false    // ..and especially not this
```
Comment (sebastienvercammen) [inline static/js/statistics.js]: Capitalize `We`, end with punctuation `this.`.

Also: 

> nor this

instead of

> neither this

File: static/js/statistics.js [hunk 5]
```diff
@@ -433,8 +437,12 @@ function redrawAppearances(appearances) {
     $.each(appearances, function (key, value) {
         var item = appearances[key]
         if (!item['hidden']) {
+            const isBounceDisabled = true // we don't need this functionality in our heatmap..
+            const scaleByRarity = false   // ..neither this..
+            const isNotifyPkmn = false    // ..and especially not this
```
Comment (sebastienvercammen) [inline static/js/statistics.js]: Same comments as above.

File: static/js/statistics.js (hunk 4 above)
Comment (JapuDCret) [reply static/js/statistics.js]: ohh man, how could I have possibly missed that...
it's updated now!
